print("                        H            H               AA              PPPPPP        PPPPPP         Y                Y")
print("                        H            H            A     A            P             P    P             P         Y        Y")
print("                        HHHHHH          AAAAAA          PPPPPP        PPPPPP                  Y")
print("                        H            H       A               A        P                   P                             Y")
print("                        H            H    A                    A      P                   P                             Y")
print("")
print("BBBBB         IIIIIIIIIIIIIII      RRRRRR       TTTTTTT      H            H      DDDDD                AA             Y                Y")
print("B          B            IIII            R          R              T            H            H      D           D           A     A               Y        Y")
print("BBBBB              IIII            RRRRR                 T             HHHHHH      D            D        AAAAAA                 Y")
print("B          B           IIII             R      R                  T            H            H      D           D       A               A               Y")
print("BBBBB         IIIIIIIIIIIIIII      R         R               T             H            H      DDDDD      A                    A             Y")
print("")
print("RRRRRR              AA                 GGGGGG      H            H                AA              V                    V              AA")
print("R          R           A     A            G                      H            H             A     A              V               V              A     A")
print("RRRRR            AAAAAA         G    GGGG        HHHHHH           AAAAAA             V          V               AAAAAA")
print("R      R           A               A      G             G       H            H        A               A              V   V                A               A")
print("R         R     A                    A    GGGGGG         H            H      A                    A              V                 A                    A")
